import localFont from "next/font/local";
import "./globals.css";

const neue = localFont({
  src: "./fonts/NeueMachina-Regular.otf",
  variable: "--font-geist-sans",
  weight: "100 900",
});


export const metadata = {
  title: "Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ neue.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
